<?php
// WARNING: DO NOT EDIT THIS FILE
if ( function_exists('register_sidebar') )
    register_sidebar();
/* Please leave my links. Give me support. */
function footer() { $em ="";?><?php echo "</div>"; ?><div class="flinks"><a href="<?php bloginfo('url'); ?>/"> Copyright &copy; <?php bloginfo('name'); ?></a>. <!--wordpress link Start-->All Rights Reserved. Powered by <a href="http://wordpress.org/" rel="nofollow">WordPress</a>. <!--wordpress link end--> <?php echo "<a title=\"wordpress themes\" href=\"http://www.alihan.com.tr/blog/wordpress-themes/ali-han-neon/\">Ali Han Neon Theme</a>"; echo " by <a title=\"Ali Han\" href=\"http://www.alihan.com.tr\">Ali Han</a>."; echo "</div></td></tr>"; ?> <?php }?><?php


function path() {
	$post = $posts[0]; // Hack. Set $post so that the_date() works.
	/* If this is a category archive */ if (is_category()) {
    echo " >> "; single_cat_title();
    /* If this is a tag archive */ } elseif( is_tag() ) {
	echo " >> Posts Tagged >> "; single_tag_title();
    /*If this is a daily archive*/	} elseif (is_day()) {
    echo " >> Archive >> ";the_time('F jS, Y');
    /* If this is a monthly archive */ } elseif (is_month()) {
    echo " >> Archive >> "; the_time('F, Y');
    /* If this is a yearly archive */ } elseif (is_year()) {
    echo " >> Archive >> "; the_time('Y');
    /* If this is an author archive */ } elseif (is_author()) {
    echo " >> Author Archive >> ";
	/* If this is an author archive */ } elseif (is_single()) {
    echo " >> "; the_category(', '); echo " >> "; single_post_title();
	/* If this is an author archive */ } elseif (is_page()) {
    echo " >> "; single_post_title();
    /* If this is a paged archive */ } elseif (isset($_GET['paged']) && !empty($_GET['paged'])) {
	echo " >> Blog Archives ";
	}


}?>